common_sheets:
  - env: dev
    sheet_id: 1MwW9BT6t6zu5_bPmTj2w13R0cwg4xWNeO-9vVv7Ilgc
  - env: test
    sheet_id: 1u_LDaWtjiliGcjPie02oYqeYDXCryZ418bjEUfAqTG8
  - env: prod
    sheet_id: 1GEowgZZqxgLHozcq-HGcl9SquCHYDySnVLbpND0VpSs
translations_sheets:
  - table_id: thfwd
    sheet_ids:
      - 1n8P9aXnV0C2cRXxF8g8-tvpcZSsb-nwUQCyoP1E3M80
      - 12drYtO6_93nmY-xG1gBgs7KSN3Q7WxJn0alrVbC3bBw
    sheet_range: A1:C200
  - table_id: thbolttech
    sheet_ids:
      - 1yRFhWpIgJApMNFTqFvm7jGarwQBGhiNLicm7hpw8gE8
      - 1YtqOs3RuUAwpDydNwnV6m6DyAQEKCT8ZenyQSZ5KAbU
    sheet_range: A1:C200
  - table_id: ussherpa
    sheet_ids:
      - 150rzgM8Qq27PIO2BuyBvueDXlxZWSn7ELd-G42xJQQs
      - 1Dz4W5tpSy9sP4U7pTdKRp1ncVLazNC8dhjonbDZ9W7I
    sheet_range: A1:B200
  - table_id: ukmsm
    sheet_ids:
      - 1bj9qkOnedtMIGDwBodIkoUpKjuioT_3KF8Tt3XuvTI0
    sheet_range: A1:B400
  - table_id: ukaviva
    sheet_ids:
      - 10SG_3XJmUmAp5Vw5yK8JNmyT7f5zBhrudBCocojuwEc
    sheet_range: A1:B400
assets_cloudfront_dists:
  - env: dev1
    dist_id: E18SKQZIZM5RSL
  - env: dev2
    dist_id: E1LKNK8J7CGIU4
  - env: dev3
    dist_id: E192G53OP91Y2
  - env: test1
    dist_id: E1QS9AW4PGE3QA
  - env: test2
    dist_id: E807R5GZE2N9D
  - env: test3
    dist_id: E2RRHKMU8BXFW0
  - env: uat1
    dist_id: E1A9CRHM8GQD8R
  - env: uat2
    dist_id: EF7AHXTC8231C
  - env: uat3
    dist_id: E16M52RGNOSXYI
  - env: demo
    dist_id: E27ZF8N34KHSXZ
  - env: prod
    dist_id: E14DLLJTYCDRJR
table_ids:
  - thfwd
  - thbolttech
  - ussherpa
environments:
  - dev1
  - dev2
  - dev3
  - test1
  - test2
  - test3
  - uat1
  - uat2
  - uat3
  - demo
  - prod
aws_regions:
  - ap-southeast-1
  - us-east-1
  - eu-west-2